################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/common_create_entities.c \
C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/create_entities_bin.c \
C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/create_entities_ref.c \
C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/create_entities_xml.c \
C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/object_id.c \
C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/read_access.c \
C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/session.c \
C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/session_info.c \
C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/submessage.c \
C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/write_access.c 

OBJS += \
./micro_xrcedds_client/src/c/core/session/common_create_entities.o \
./micro_xrcedds_client/src/c/core/session/create_entities_bin.o \
./micro_xrcedds_client/src/c/core/session/create_entities_ref.o \
./micro_xrcedds_client/src/c/core/session/create_entities_xml.o \
./micro_xrcedds_client/src/c/core/session/object_id.o \
./micro_xrcedds_client/src/c/core/session/read_access.o \
./micro_xrcedds_client/src/c/core/session/session.o \
./micro_xrcedds_client/src/c/core/session/session_info.o \
./micro_xrcedds_client/src/c/core/session/submessage.o \
./micro_xrcedds_client/src/c/core/session/write_access.o 

C_DEPS += \
./micro_xrcedds_client/src/c/core/session/common_create_entities.d \
./micro_xrcedds_client/src/c/core/session/create_entities_bin.d \
./micro_xrcedds_client/src/c/core/session/create_entities_ref.d \
./micro_xrcedds_client/src/c/core/session/create_entities_xml.d \
./micro_xrcedds_client/src/c/core/session/object_id.d \
./micro_xrcedds_client/src/c/core/session/read_access.d \
./micro_xrcedds_client/src/c/core/session/session.d \
./micro_xrcedds_client/src/c/core/session/session_info.d \
./micro_xrcedds_client/src/c/core/session/submessage.d \
./micro_xrcedds_client/src/c/core/session/write_access.d 


# Each subdirectory must supply rules for building sources it contributes
micro_xrcedds_client/src/c/core/session/common_create_entities.o: C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/common_create_entities.c micro_xrcedds_client/src/c/core/session/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/profile/shared_memory" -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/util" -I"C:/stm32_microros/firmware/third_party/microros/include" -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
micro_xrcedds_client/src/c/core/session/create_entities_bin.o: C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/create_entities_bin.c micro_xrcedds_client/src/c/core/session/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/profile/shared_memory" -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/util" -I"C:/stm32_microros/firmware/third_party/microros/include" -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
micro_xrcedds_client/src/c/core/session/create_entities_ref.o: C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/create_entities_ref.c micro_xrcedds_client/src/c/core/session/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/profile/shared_memory" -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/util" -I"C:/stm32_microros/firmware/third_party/microros/include" -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
micro_xrcedds_client/src/c/core/session/create_entities_xml.o: C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/create_entities_xml.c micro_xrcedds_client/src/c/core/session/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/profile/shared_memory" -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/util" -I"C:/stm32_microros/firmware/third_party/microros/include" -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
micro_xrcedds_client/src/c/core/session/object_id.o: C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/object_id.c micro_xrcedds_client/src/c/core/session/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/profile/shared_memory" -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/util" -I"C:/stm32_microros/firmware/third_party/microros/include" -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
micro_xrcedds_client/src/c/core/session/read_access.o: C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/read_access.c micro_xrcedds_client/src/c/core/session/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/profile/shared_memory" -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/util" -I"C:/stm32_microros/firmware/third_party/microros/include" -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
micro_xrcedds_client/src/c/core/session/session.o: C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/session.c micro_xrcedds_client/src/c/core/session/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/profile/shared_memory" -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/util" -I"C:/stm32_microros/firmware/third_party/microros/include" -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
micro_xrcedds_client/src/c/core/session/session_info.o: C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/session_info.c micro_xrcedds_client/src/c/core/session/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/profile/shared_memory" -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/util" -I"C:/stm32_microros/firmware/third_party/microros/include" -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
micro_xrcedds_client/src/c/core/session/submessage.o: C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/submessage.c micro_xrcedds_client/src/c/core/session/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/profile/shared_memory" -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/util" -I"C:/stm32_microros/firmware/third_party/microros/include" -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
micro_xrcedds_client/src/c/core/session/write_access.o: C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/core/session/write_access.c micro_xrcedds_client/src/c/core/session/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/profile/shared_memory" -I"C:/stm32_microros/firmware/third_party/micro_xrcedds_client/src/c/util" -I"C:/stm32_microros/firmware/third_party/microros/include" -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-micro_xrcedds_client-2f-src-2f-c-2f-core-2f-session

clean-micro_xrcedds_client-2f-src-2f-c-2f-core-2f-session:
	-$(RM) ./micro_xrcedds_client/src/c/core/session/common_create_entities.cyclo ./micro_xrcedds_client/src/c/core/session/common_create_entities.d ./micro_xrcedds_client/src/c/core/session/common_create_entities.o ./micro_xrcedds_client/src/c/core/session/common_create_entities.su ./micro_xrcedds_client/src/c/core/session/create_entities_bin.cyclo ./micro_xrcedds_client/src/c/core/session/create_entities_bin.d ./micro_xrcedds_client/src/c/core/session/create_entities_bin.o ./micro_xrcedds_client/src/c/core/session/create_entities_bin.su ./micro_xrcedds_client/src/c/core/session/create_entities_ref.cyclo ./micro_xrcedds_client/src/c/core/session/create_entities_ref.d ./micro_xrcedds_client/src/c/core/session/create_entities_ref.o ./micro_xrcedds_client/src/c/core/session/create_entities_ref.su ./micro_xrcedds_client/src/c/core/session/create_entities_xml.cyclo ./micro_xrcedds_client/src/c/core/session/create_entities_xml.d ./micro_xrcedds_client/src/c/core/session/create_entities_xml.o ./micro_xrcedds_client/src/c/core/session/create_entities_xml.su ./micro_xrcedds_client/src/c/core/session/object_id.cyclo ./micro_xrcedds_client/src/c/core/session/object_id.d ./micro_xrcedds_client/src/c/core/session/object_id.o ./micro_xrcedds_client/src/c/core/session/object_id.su ./micro_xrcedds_client/src/c/core/session/read_access.cyclo ./micro_xrcedds_client/src/c/core/session/read_access.d ./micro_xrcedds_client/src/c/core/session/read_access.o ./micro_xrcedds_client/src/c/core/session/read_access.su ./micro_xrcedds_client/src/c/core/session/session.cyclo ./micro_xrcedds_client/src/c/core/session/session.d ./micro_xrcedds_client/src/c/core/session/session.o ./micro_xrcedds_client/src/c/core/session/session.su ./micro_xrcedds_client/src/c/core/session/session_info.cyclo ./micro_xrcedds_client/src/c/core/session/session_info.d ./micro_xrcedds_client/src/c/core/session/session_info.o ./micro_xrcedds_client/src/c/core/session/session_info.su ./micro_xrcedds_client/src/c/core/session/submessage.cyclo ./micro_xrcedds_client/src/c/core/session/submessage.d ./micro_xrcedds_client/src/c/core/session/submessage.o ./micro_xrcedds_client/src/c/core/session/submessage.su ./micro_xrcedds_client/src/c/core/session/write_access.cyclo ./micro_xrcedds_client/src/c/core/session/write_access.d ./micro_xrcedds_client/src/c/core/session/write_access.o ./micro_xrcedds_client/src/c/core/session/write_access.su

.PHONY: clean-micro_xrcedds_client-2f-src-2f-c-2f-core-2f-session

